### ISSUE TITLE
VS Scrollama

### ISSUE THREAD

**Issue by clarknelson** [russellgoldenberg/enter-view#12]
Hello, love your plugin Scrollama! I noticed a similar API, should we be using this framework instead?

Thank you :)

**Comment by russellsamora** [comment]
they have different goals - this library is quite literally what it sounds like, know when an element enters into the viewport. Scrollama is designed specifically for scroll-driven storytelling triggers with a few features/approaches tailored to that use case. They can be both be used for a lot of the same stuff with some different hacks and configurations since they are ultimately both more abstractly about detecting when an element is somewhere on the page.
